package com.example.pathtrackerapp.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFF006A60)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF74F8E5)
val LightOnPrimaryContainer = Color(0xFF00201C)
val LightInversePrimary = Color(0xFF53DBC9)
val LightSecondary = Color(0xFF7E5700)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDEAB)
val LightOnSecondaryContainer = Color(0xFF281900)
val LightBackground = Color(0xFFFAFDFB)
val LightOnBackground = Color(0xFF191C1B)
val LightSurface = Color(0xFFEEF2F0)
val LightOnSurface = Color(0xFF191C1B)
val LightOnSurfaceVariant = Color(0xFF3F4947)
val LightSurfaceContainerLowest = Color(0xFFF3F5F3)
val LightSurfaceContainerLow = Color(0xFFF2F5F3)
val LightSurfaceContainer = Color(0xFFEDEFED)
val LightSurfaceContainerHigh = Color(0xFFE7E9E7)
val LightSurfaceContainerHighest = Color(0xFFDCE0DE)
val LightInverseSurface = Color(0xFF2E3130)
val LightInverseOnSurface = Color(0xFFEFF1EF)
val LightOutline = Color(0xFF6F7977)
val LightOutlineVariant = Color(0xFFBFC9C6)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

// Dark Theme Colors
val DarkPrimary = Color(0xFF53DBC9)
val DarkOnPrimary = Color(0xFF003731)
val DarkPrimaryContainer = Color(0xFF005048)
val DarkOnPrimaryContainer = Color(0xFF74F8E5)
val DarkInversePrimary = Color(0xFF006A60)
val DarkSecondary = Color(0xFFFCBB4A)
val DarkOnSecondary = Color(0xFF432C00)
val DarkSecondaryContainer = Color(0xFF604100)
val DarkOnSecondaryContainer = Color(0xFFFFDEAB)
val DarkBackground = Color(0xFF191C1B)
val DarkOnBackground = Color(0xFFE1E3E1)
val DarkSurface = Color(0xFF222524)
val DarkOnSurface = Color(0xFFE1E3E1)
val DarkOnSurfaceVariant = Color(0xFFBFC9C6)
val DarkSurfaceContainerLowest = Color(0xFF1E2120)
val DarkSurfaceContainerLow = Color(0xFF262928)
val DarkSurfaceContainer = Color(0xFF2F3231)
val DarkSurfaceContainerHigh = Color(0xFF3A3D3C)
val DarkSurfaceContainerHighest = Color(0xFF454847)
val DarkInverseSurface = Color(0xFFE1E3E1)
val DarkInverseOnSurface = Color(0xFF191C1B)
val DarkOutline = Color(0xFF899390)
val DarkOutlineVariant = Color(0xFF3F4947)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)